// Auto-generated by scripts/sync-skills.mjs — do not edit manually.
// Run `npm run sync-skills` to regenerate from the skills repository.

export type SkillCategory =
  | "rust"
  | "c"
  | "go"
  | "frontend"
  | "shaders"
  | "cuda"
  | "ai"
  | "tools";

export interface Skill {
  name: string;
  title: string;
  description: string;
  category: SkillCategory;
  references: number;
}

export const categoryMeta: Record<
  SkillCategory,
  { label: string; color: string; borderColor: string }
> = {
  rust: { label: "Rust", color: "text-orange-600 dark:text-orange-400 bg-orange-500/10", borderColor: "border-t-orange-500" },
  c: { label: "C", color: "text-red-600 dark:text-red-400 bg-red-500/10", borderColor: "border-t-red-500" },
  go: { label: "Go", color: "text-cyan-600 dark:text-cyan-400 bg-cyan-500/10", borderColor: "border-t-cyan-500" },
  frontend: { label: "Frontend & Web", color: "text-blue-600 dark:text-blue-400 bg-blue-500/10", borderColor: "border-t-blue-500" },
  shaders: { label: "3D Graphics & Shaders", color: "text-violet-600 dark:text-violet-400 bg-violet-500/10", borderColor: "border-t-violet-500" },
  cuda: { label: "GPU / CUDA", color: "text-lime-600 dark:text-lime-400 bg-lime-500/10", borderColor: "border-t-lime-500" },
  ai: { label: "AI & Data", color: "text-emerald-600 dark:text-emerald-400 bg-emerald-500/10", borderColor: "border-t-emerald-500" },
  tools: { label: "Tools & Workflows", color: "text-neutral-600 dark:text-neutral-400 bg-neutral-500/10", borderColor: "border-t-neutral-500" },
};

export const skills: Skill[] = [
  // ── Rust ────────────────────────────────────────────────
  {
    name: "async-stripe",
    title: "Async Stripe",
    description:
      "Development guide for the async-stripe Rust crate: strongly-typed async Stripe API bindings generated from OpenAPI spec",
    category: "rust",
    references: 2,
  },
  {
    name: "clerk-rs-sdk",
    title: "Clerk RS SDK",
    description:
      "clerk-rs Rust SDK for Clerk authentication: client setup, typed API calls, JWT validation, and framework middleware (Axum, Actix, Rocket...",
    category: "rust",
    references: 1,
  },
  {
    name: "rust-arc",
    title: "Rust Arc",
    description:
      "Rust Arc (Atomically Reference Counted) smart pointer for thread-safe shared ownership",
    category: "rust",
    references: 2,
  },
  {
    name: "rust-async",
    title: "Rust Async",
    description:
      "Rust async/await programming patterns, futures, streams, concurrency, and runtime usage",
    category: "rust",
    references: 3,
  },
  {
    name: "rust-axum",
    title: "Rust Axum",
    description:
      "Axum 0.8 web framework for Rust: routing, extractors, handlers, middleware, responses, state, WebSockets, SSE, error handling, testing...",
    category: "rust",
    references: 6,
  },
  {
    name: "rust-best-practices",
    title: "Rust Best Practices",
    description:
      "Idiomatic Rust patterns, API design, and cross-cutting best practices for writing clean, performant, and maintainable Rust code",
    category: "rust",
    references: 5,
  },
  {
    name: "rust-concurrency",
    title: "Rust Concurrency",
    description:
      "Rust concurrency and parallelism patterns: threads, message passing with channels, shared state with Mutex and Arc...",
    category: "rust",
    references: 3,
  },
  {
    name: "rust-crypto",
    title: "Rust Crypto",
    description:
      "Rust cryptography with RustCrypto crates: AES-GCM and ChaCha20Poly1305 authenticated encryption, HMAC message authentication...",
    category: "rust",
    references: 8,
  },
  {
    name: "rust-ownership",
    title: "Rust Ownership",
    description:
      "Rust ownership, borrowing, and lifetime system from the Nomicon, Rust Book, and Rust Reference",
    category: "rust",
    references: 3,
  },
  {
    name: "rust-seaorm",
    title: "Rust SeaORM",
    description:
      "SeaORM async ORM for Rust (1.x stable + 2.0 RC): entity definition, CRUD operations, relations, migrations, transactions...",
    category: "rust",
    references: 4,
  },
  {
    name: "rust-tokio",
    title: "Rust Tokio",
    description:
      "Tokio async runtime for Rust: task spawning, JoinSet, shared state, channels (mpsc/oneshot/broadcast/watch)...",
    category: "rust",
    references: 6,
  },
  {
    name: "rust-traits",
    title: "Rust Traits",
    description:
      "Rust trait system best practices, patterns, and idiomatic usage",
    category: "rust",
    references: 5,
  },

  // ── C ───────────────────────────────────────────────────
  {
    name: "c-best-practices",
    title: "C Best Practices",
    description:
      "C programming best practices, idiomatic patterns, and safe coding for modern C (C11/C17/C23)",
    category: "c",
    references: 5,
  },

  // ── Go ──────────────────────────────────────────────────
  {
    name: "go-best-practices",
    title: "Go Best Practices",
    description:
      "Go (Golang) best practices, idioms, and modern patterns for writing clean, performant, and maintainable Go code",
    category: "go",
    references: 5,
  },

  // ── Frontend & Web ──────────────────────────────────────
  {
    name: "angular-best-practices",
    title: "Angular Best Practices",
    description:
      "Angular v20+ best practices - standalone components, signals, dependency injection, routing, reactive forms, HttpClient, control flow...",
    category: "frontend",
    references: 8,
  },
  {
    name: "clerk-best-practices",
    title: "Clerk Best Practices",
    description:
      "Clerk authentication best practices for Next.js (App Router).",
    category: "frontend",
    references: 10,
  },
  {
    name: "coss-ui",
    title: "Coss UI",
    description:
      "coss ui component library built on Base UI and Tailwind CSS for React applications.",
    category: "frontend",
    references: 5,
  },
  {
    name: "drizzle-orm",
    title: "Drizzle ORM",
    description:
      "Drizzle ORM for TypeScript/PostgreSQL: type-safe schema definition, queries, migrations, and Neon serverless integration",
    category: "frontend",
    references: 5,
  },
  {
    name: "fumadocs",
    title: "Fumadocs",
    description:
      "Fumadocs documentation framework for Next.js - project setup, content sources, MDX, layouts, UI components, search, OpenAPI, and i18n",
    category: "frontend",
    references: 7,
  },
  {
    name: "neon-best-practices",
    title: "Neon Best Practices",
    description:
      "Neon serverless Postgres best practices for Next.js App Router: setup, connection pooling, branching, autoscaling, and authentication",
    category: "frontend",
    references: 4,
  },
  {
    name: "next-best-practices",
    title: "Next Best Practices",
    description:
      "Next.js best practices for the App Router (v14/v15/v16+)",
    category: "frontend",
    references: 19,
  },
  {
    name: "primeng",
    title: "PrimeNG",
    description:
      "PrimeNG UI component library for Angular with 80+ components, theming, and accessibility",
    category: "frontend",
    references: 6,
  },
  {
    name: "tailwind-best-practices",
    title: "Tailwind Best Practices",
    description:
      "Tailwind CSS v4 best practices for Next.js App Router. CSS-first config with @theme, @utility, @custom-variant, @plugin directives",
    category: "frontend",
    references: 9,
  },
  {
    name: "tanstack-form",
    title: "TanStack Form",
    description:
      "TanStack Form v1.x for React: type-safe, performant, composable form management with validation, arrays, linked fields, listeners...",
    category: "frontend",
    references: 5,
  },
  {
    name: "tanstack-query",
    title: "TanStack Query",
    description:
      "TanStack Query (React Query) v5 best practices for fetching, caching and updating server state in React",
    category: "frontend",
    references: 4,
  },
  {
    name: "tanstack-store",
    title: "TanStack Store",
    description:
      "TanStack Store framework-agnostic reactive state management with Store, Derived, Effect, and batch.",
    category: "frontend",
    references: 2,
  },
  {
    name: "tanstack-table",
    title: "TanStack Table",
    description:
      "TanStack Table v8 headless UI library for building type-safe tables and datagrids in React, Vue, Solid, Svelte, Qwik, Angular, and Lit",
    category: "frontend",
    references: 4,
  },

  // ── 3D Graphics & Shaders ───────────────────────────────
  {
    name: "caustics-r3f",
    title: "Caustics R3F",
    description:
      "Real-time caustic light effects for React Three Fiber and Three.js using GLSL shaders, render targets (FBO), normal extraction...",
    category: "shaders",
    references: 2,
  },
  {
    name: "moebius-post-processing",
    title: "Moebius Post Processing",
    description:
      "Moebius-style (Jean Giraud) NPR post-processing shaders for React Three Fiber and Three.js.",
    category: "shaders",
    references: 2,
  },
  {
    name: "painterly-kuwahara-shader",
    title: "Painterly Kuwahara Shader",
    description:
      "Painterly post-processing shaders using the Kuwahara filter for React Three Fiber, Three.js, and WebGL.",
    category: "shaders",
    references: 3,
  },
  {
    name: "post-processing-shaders",
    title: "Post Processing Shaders",
    description:
      "Creative post-processing shader effects for React Three Fiber and Three.js using GLSL and the pmndrs/postprocessing library",
    category: "shaders",
    references: 3,
  },
  {
    name: "react-three-fiber",
    title: "React Three Fiber",
    description:
      "React Three Fiber (R3F) — the React renderer for Three.js.",
    category: "shaders",
    references: 5,
  },
  {
    name: "retro-dithering-crt",
    title: "Retro Dithering CRT",
    description:
      "Retro dithering, color quantization, and CRT post-processing shader effects for React Three Fiber and Three.js using GLSL and the...",
    category: "shaders",
    references: 3,
  },
  {
    name: "tsl-webgpu",
    title: "TSL WebGPU",
    description:
      "TSL (Three.js Shading Language) and WebGPU shader development with Three.js.",
    category: "shaders",
    references: 3,
  },
  {
    name: "volumetric-lighting",
    title: "Volumetric Lighting",
    description:
      "Real-time volumetric lighting with post-processing and raymarching for React Three Fiber and Three.js",
    category: "shaders",
    references: 6,
  },
  {
    name: "web-3d-shaders",
    title: "Web 3D Shaders",
    description:
      "Shaders and real-time 3D on the Web with GLSL, Three.js, React Three Fiber, and WebGPU.",
    category: "shaders",
    references: 7,
  },

  // ── GPU / CUDA ──────────────────────────────────────────
  {
    name: "cuda-best-practices",
    title: "CUDA Best Practices",
    description:
      "NVIDIA CUDA C/C++ GPU programming best practices and performance optimization",
    category: "cuda",
    references: 5,
  },

  // ── AI & Data ───────────────────────────────────────────
  {
    name: "rag-pgvector",
    title: "RAG pgvector",
    description:
      "RAG (Retrieval-Augmented Generation) pipelines with pgvector and PostgreSQL: vector storage, HNSW/IVFFlat indexes...",
    category: "ai",
    references: 4,
  },

  // ── Tools & Workflows ───────────────────────────────────
  {
    name: "agent-swarm",
    title: "Agent Swarm",
    description:
      "Best practices for orchestrating Claude Code agent teams (swarm mode)",
    category: "tools",
    references: 3,
  },
  {
    name: "mcp-server-dev",
    title: "MCP Server Dev",
    description:
      "Build MCP (Model Context Protocol) servers in TypeScript with @modelcontextprotocol/sdk",
    category: "tools",
    references: 4,
  },
  {
    name: "skill-creator",
    title: "Skill Creator",
    description:
      "Interactive guide for creating new skills (or updating existing skills) that extend Claude's capabilities with specialized knowledge...",
    category: "tools",
    references: 3,
  },
];

export const GITHUB_REPO = "https://github.com/ArthurDEV44/skills";
